function y = lftOptSet(varargin)
                LocalOptions = struct('TolFun', 1e-3,...
                                      'MaxStep', [],...
                                      'NumberOfSteps', 2,...
                                      'PolynomialDegree', [],...
                                      'RelTolX', 1e-3,...
                                      'MinNormGrad', 1e-3,...
                                      'EpsilonLambda', 1e-6,...
                                      'MaxIter',20,...
                                      'Display', 'off',...
                                      'StartOptimSample', 1);
                                  
                for i=1:nargin/2
                    if ischar(varargin{i*2})
                        LocalValue = char(varargin(i*2));
                    else
                        LocalValue = varargin{i*2};
                    end;
                    LocalOptions.(char(varargin(i*2-1))) = LocalValue;
                end;
                y = LocalOptions;
end