function y = lftSet(varargin)
                LocalOptions = struct('RelTol', 1e-3,...
                                      'AbsTol', 1e-6,...
                                      'MaxOrder', 5,...
                                      'BDF', 'off',...
                                      'InitialStep', 1e-6,...
                                      'MaxStep', [],...
                                      'NumberOfSteps', [],...
                                      'ShowIntTime', false,...
                                      'SolutionInterpMethod', 'linear',...
                                      'OversamplingMethod', 'linear',... 
                                      'SolutionTimeSpan', [],...
                                      'Sensitivity', 0,... % [0, p#, u#]
                                      'SensAlgorithm', 'ode15s',... % ['ode15s, backwardEuler']
                                      'CommonTerms', []);
                for i=1:nargin/2
                    if ischar(varargin{i*2})
                        LocalValue = char(varargin(i*2));
                    else
                        LocalValue = varargin{i*2};
                    end;
                    LocalOptions.(char(varargin(i*2-1))) = LocalValue;
                end;
                y = LocalOptions;
end